// ── AnimeVault Ad-Blocker Service Worker ──────────────────────────────────
// Intercepts fetch requests from embed iframes and blocks known ad/tracker domains.
// Register this from your app with: navigator.serviceWorker.register('/sw.js')

const AD_DOMAINS = [
  // Ad networks
  'doubleclick.net',
  'googlesyndication.com',
  'googleadservices.com',
  'google-analytics.com',
  'googletagmanager.com',
  'adservice.google.com',
  'pagead2.googlesyndication.com',
  'adserver.google.com',
  'pubads.g.doubleclick.net',
  'securepubads.g.doubleclick.net',
  'adserver.adtechus.com',
  'adserver.adtech.de',
  'ad.doubleclick.net',
  'adclick.g.doubleclick.net',
  'googleads.g.doubleclick.net',
  'cm.g.doubleclick.net',
  'tpc.googlesyndication.com',

  // Common ad platforms
  'exoclick.com',
  'exosrv.com',
  'popads.net',
  'popadscdn.net',
  'propellerads.com',
  'propellerclick.com',
  'trafficfactory.biz',
  'adsterra.com',
  'adsterra.net',
  'adsterra.org',
  'adcash.com',
  'adcash.net',
  'adbucks.io',
  'adbucks.net',
  'adf.ly',
  'adfoc.us',
  'adultad.net',
  'adventory.com',
  'advertising.com',
  'adnxs.com',
  'adsafeprotected.com',
  'adsrvr.org',
  'adtech.de',
  'advertising.aol.com',
  'aol.com',
  'apmebf.com',
  'atdmt.com',
  'bluekai.com',
  'brainlyads.com',
  'brightcove.com',
  'casalemedia.com',
  'clickaider.com',
  'clickfuse.com',
  'clickinc.com',
  'clicksor.com',
  'clickwink.com',
  'cloudfront.net',
  'contentabc.com',
  'contextweb.com',
  'cpxinteractive.com',
  'criteo.com',
  'criteo.net',
  'crwdcntrl.net',
  'de17a.com',
  'demdex.net',
  'dmtry.com',
  'doublepimp.com',
  'dynad.net',
  'ecircle.com',
  'effectivemeasure.net',
  'engine.adglare.net',
  'engageya.com',
  'exdynsrv.com',
  'exelator.com',
  'eyenewton.ru',
  'fcdn.co',
  'fifty.com',
  'flashtalking.com',
  'focalink.com',
  'fout.jp',
  'freewheel.tv',
  'fusionads.net',
  'gammapro.com',
  'gemius.pl',
  'goadservices.com',
  'gravatar.com',
  'gssprt.com',
  'gssptr.com',
  'guj.de',
  'heias.com',
  'hi-stats.com',
  'hit.gemius.pl',
  'hitslink.com',
  'hotlog.ru',
  'hp.com',
  'hs-analytics.net',
  'hubspot.com',
  'hybrid.ai',
  'hyperroll.com',
  'ia-h.com',
  'id5-sync.com',
  'inmobi.com',
  'intentiq.com',
  'intercom.com',
  'internetvideoarchive.com',
  'iponweb.com',
  'issuu.com',
  'ivwbox.de',
  'js.adscale.de',
  'js.genieessp.com',
  'juicyads.com',
  'kargo.com',
  'kissmetrics.com',
  'komoona.com',
  'leadbolt.com',
  'lijit.com',
  'linkedin.com',
  'livefyre.com',
  'liveinternet.ru',
  'lotame.com',
  'media.net',
  'media6degrees.com',
  'mediaforge.com',
  'mediaplex.com',
  'mediaset.net',
  'mediashakers.com',
  'mediamath.com',
  'mercadopago.com',
  'microsoft.com',
  'moatads.com',
  'mookie1.com',
  'moonshine.agency',
  'mrskincash.com',
  'myads.com',
  'mydas.mobi',
  'mymetrics.ai',
  'myvisualiq.com',
  'nend.net',
  'netaffiliation.com',
  'neustar.biz',
  'newrelic.com',
  'nexage.com',
  'nexstair.com',
  'ns1-cdn.org',
  'nuggad.net',
  'nuviad.net',
  'o2.co.uk',
  'oath.com',
  'oewa.at',
  'ogury.com',
  'openx.net',
  'openx.org',
  'optimizely.com',
  'outbrain.com',
  'outbrain.net',
  'owneriq.com',
  'parsely.com',
  'peer39.com',
  'peerset.com',
  'pharore.com',
  'photorank.me',
  'pinterest.com',
  'piwik.org',
  'plista.com',
  'pontomobi.com',
  'poprule.com',
  'prebid.org',
  'pressflex.com',
  'pro-market.net',
  'pubmatic.com',
  'pusher.com',
  'quantcast.com',
  'quantserve.com',
  'quora.com',
  'radiatemedia.com',
  'rambler.ru',
  'realsrv.com',
  'reddit.com',
  'redditmedia.com',
  'reson8.com',
  'revcontent.com',
  'revjet.com',
  'rfihub.com',
  'rlcdn.com',
  'rotaban.ru',
  'rubiconproject.com',
  'sail-horizon.com',
  'savannahis.com',
  'scanscout.com',
  'scorecardresearch.com',
  'scrubtheweb.com',
  'sekindo.com',
  'serving-sys.com',
  'shareaholic.com',
  'sharethis.com',
  'simpli.fi',
  'smaato.net',
  'smartyads.com',
  'snapchat.com',
  'socialtwist.com',
  'sojern.com',
  'sonobi.com',
  'sortable.com',
  'specificmedia.net',
  'sponsorpay.com',
  'spot.xyz',
  'spotxchange.com',
  'springserve.com',
  'stackadapt.com',
  'startapp.com',
  'static.adsafeproducted.com',
  'stripe.com',
  'stumbleupon.com',
  'sumo.com',
  'sumome.com',
  'swoop.com',
  'taboola.com',
  'taboolasyndication.com',
  'tagger.media',
  'taleo.net',
  'tapad.com',
  'tapjoy.com',
  'tawk.to',
  'teads.tv',
  'teemo.xyz',
  'theads.me',
  'thetracktor.com',
  'tidaltv.com',
  'tinypass.com',
  'tmogul.com',
  'trafficmanager.net',
  'trafficfacto.com',
  'trafficfactory.com',
  'traffichaus.com',
  'trafficjunky.com',
  'trafficjunky.net',
  'trafficstars.com',
  'trafficvance.com',
  'tremorhub.com',
  'trendmd.com',
  'triplelift.com',
  'trueffect.com',
  'trustx.org',
  'tubemogul.com',
  'turn.com',
  'tweetdeck.com',
  'twimg.com',
  'twitter.com',
  'tynt.com',
  'ubembed.com',
  'udmserve.net',
  'ultraad.com',
  'unanimis.co.uk',
  'undertone.com',
  'unrulymedia.com',
  'upapi.net',
  'valueclick.com',
  'valueclickmedia.com',
  'verisign.com',
  'verticalacuity.com',
  'vertamedia.com',
  'vibrantmedia.com',
  'videologygroup.com',
  'vidible.tv',
  'viewbix.com',
  'viglink.com',
  'visx.net',
  'viziosphere.com',
  'vkontakte.ru',
  'vli.pl',
  'vungle.com',
  'wardenclyffe.com',
  'warp2.com',
  'webads.co.nz',
  'weborama.com',
  'weborama.fr',
  'webtrends.com',
  'webtrendslive.com',
  'whatsapp.com',
  'widgets.com',
  'widespace.com',
  'wikia.com',
  'wpadmngr.com',
  'wp.com',
  'wpn.net',
  'wsod.com',
  'www-google-analytics.com',
  'xad.com',
  'xaxis.com',
  'xdmserv.net',
  'xhamster.com',
  'xnxx.com',
  'xvideos.com',
  'yahoo.com',
  'yandex.com',
  'yandex.ru',
  'yieldmo.com',
  'yieldoptimizer.com',
  'yieldtraffic.com',
  'yldbt.com',
  'yoc.com',
  'youtube.com',
  'yumenetworks.com',
  'zanox.com',
  'zergnet.com',
  'zeusclicks.com',
  'zucks.net',

  // Embed-specific ad domains
  'animeplay.cfd',
  'megaplay.cfd',
  'vidnest.fun',
  'ninjasheild.stream',
  'dropfile.cc',
  'api.cinetaro.buzz',
  'vidsrc.xyz',
  'vidsrc.pro',
  'vidsrc.to',
  'vidsrc.me',
  'embed.su',
  'vidsrc.su',
  'vsembed.su',
  'vidsrc.icu',
  'vidsrc.net',
  'vvd.lol',
  'multiembed.com',
  'multiembed.mov',
  '2embed.cc',
  '2embed.to',
  '2embed.org',
  'autoembed.cc',
  'embedsb.com',
  'embed.nicovideo.jp',
  'gogoanime',
  'gogocdn',
  'animepahe',
  'aniwatch',
  '9anime',
  'zoro.to',
  'animeheaven',
  'kissanime',
];

// Track domains that include these substrings
const AD_KEYWORDS = [
  'ad',
  'ads',
  'banner',
  'popup',
  'track',
  'tracking',
  'analytics',
  'metrics',
  'beacon',
  'pixel',
  'impression',
  'sponsor',
  'promo',
  'campaign',
  'click',
  'affiliate',
  'redirect',
  'counter',
  'stats',
  'stat',
  'adservice',
  'adserver',
  'adtech',
  'advert',
  'advertising',
  'marketing',
  'target',
  'retarget',
  'traffic',
  'traffic2',
  'realvu',
  'realvu',
  'smartad',
  'smartads',
  'smartadserver',
];

const AD_FILE_EXTENSIONS = [
  '.js',
  '.jsonp',
];

self.addEventListener('install', (event) => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(clients.claim());
});

// Domains that should NEVER be blocked by ad-filtering (e.g. media upload CDNs)
const ALLOWLIST_DOMAINS = [
  'api.cloudinary.com',
  'res.cloudinary.com',
];

self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  const hostname = url.hostname.toLowerCase();
  const selfHostname = self.location?.hostname || '';

  // — ALWAYS pass through allowlisted domains (e.g. Cloudinary uploads) —
  for (const allowed of ALLOWLIST_DOMAINS) {
    if (hostname === allowed || hostname.endsWith('.' + allowed)) {
      return;
    }
  }

  // Block known ad domains
  for (const adDomain of AD_DOMAINS) {
    if (hostname === adDomain || hostname.endsWith('.' + adDomain)) {
      return event.respondWith(new Response(null, { status: 204 }));
    }
  }

  // Block requests with ad keywords in path (but allow media files through)
  for (const keyword of AD_KEYWORDS) {
    const path = url.pathname.toLowerCase();
    if (path.includes(keyword)) {
      const isMedia = path.match(/\.(mp4|webm|m3u8|ts|m4s|mp3|ogg|wav|flac|mkv|avi)$/i);
      if (!isMedia) {
        return event.respondWith(new Response(null, { status: 204 }));
      }
    }
  }

  // Allow all other requests through
  return;
});
