const DB_NAME='animevault_android_downloads';
const DB_VERSION=2;
const STORE='items';
function openDb(){return new Promise((resolve,reject)=>{if(typeof indexedDB==='undefined')return reject(new Error('Offline storage is unavailable on this device.'));const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'id'});};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error||new Error('Could not open offline storage.'));});}
export async function listDownloads(){const db=await openDb();return new Promise((resolve,reject)=>{const req=db.transaction(STORE,'readonly').objectStore(STORE).getAll();req.onsuccess=()=>resolve((req.result||[]).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)));req.onerror=()=>reject(req.error);});}
export async function getDownload(id){const db=await openDb();return new Promise((resolve,reject)=>{const req=db.transaction(STORE,'readonly').objectStore(STORE).get(id);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error);});}
async function put(item){const db=await openDb();return new Promise((resolve,reject)=>{const req=db.transaction(STORE,'readwrite').objectStore(STORE).put(item);req.onsuccess=()=>resolve(item);req.onerror=()=>reject(req.error);});}
export async function removeDownload(id){const db=await openDb();return new Promise((resolve,reject)=>{const req=db.transaction(STORE,'readwrite').objectStore(STORE).delete(id);req.onsuccess=resolve;req.onerror=()=>reject(req.error);});}
export async function clearDownloads(){const db=await openDb();return new Promise((resolve,reject)=>{const req=db.transaction(STORE,'readwrite').objectStore(STORE).clear();req.onsuccess=resolve;req.onerror=()=>reject(req.error);});}
export async function getDownloadStorageEstimate(){try{if(!navigator.storage?.estimate)return null;return await navigator.storage.estimate();}catch{return null;}}
export async function saveDownload({id,title,image,episode,url,type='mp4',onProgress}){if(type!=='mp4')throw new Error('Only direct MP4 files can be saved for offline playback right now.');if(!url)throw new Error('No direct download URL was returned.');const existing=await getDownload(id);if(existing?.blob&&existing.status==='complete')return existing;const createdAt=existing?.createdAt||Date.now();await put({id,title,image,episode,url,type,status:'downloading',progress:0,createdAt});try{const response=await fetch(url);if(!response.ok)throw new Error(`Download failed (${response.status}).`);const total=Number(response.headers.get('content-length'))||0;let received=0;let blob;if(response.body?.getReader){const reader=response.body.getReader();const chunks=[];for(;;){const {done,value}=await reader.read();if(done)break;chunks.push(value);received+=value.byteLength;const progress=total?Math.min(99,Math.round(received/total*100)):0;await put({id,title,image,episode,url,type,status:'downloading',progress,createdAt});onProgress?.(progress);}blob=new Blob(chunks,{type:'video/mp4'});}else blob=await response.blob();const item={id,title,image,episode,url,type,status:'complete',progress:100,size:blob.size,blob,createdAt};await put(item);return item;}catch(error){await removeDownload(id).catch(()=>{});throw error;}}
export async function getDownloadUrl(id){const item=await getDownload(id);if(!item?.blob||item.status!=='complete')return null;return URL.createObjectURL(item.blob);}
