import React,{useEffect,useRef,useState}from'react';
import{ArrowLeft,Maximize,Minimize,Play,SkipBack,SkipForward}from'lucide-react';
import{fetchMovieDetails,fetchTVDetails,fetchTVSeasonDetails,resolveDirectMediaSource,MEDIA_SOURCE_PROVIDERS,DEFAULT_MEDIA_SOURCE_PROVIDER}from'../api/movies';
import AndroidVideoPlayer from'../components/AndroidVideoPlayer';
import{useUser}from'../../api/UserContext';

export default function DramaDetailPage({params={},goBack,navigate}){
 const{user,setAuthTab}=useUser(),id=params?.id,type=String(params?.mediaType||params?.type||'tv').toLowerCase()==='movie'?'movie':'tv',initialTitle=params?.title;
 const[details,setDetails]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[season,setSeason]=useState(1),[episode,setEpisode]=useState(1),[episodes,setEpisodes]=useState([]),[playing,setPlaying]=useState(false),[source,setSource]=useState(''),[sourceLoading,setSourceLoading]=useState(false),[provider,setProvider]=useState(DEFAULT_MEDIA_SOURCE_PROVIDER),[fullscreen,setFullscreen]=useState(false);const playerRef=useRef(null);
 useEffect(()=>{let dead=false;(async()=>{if(!id){setError('Missing movie or TV show ID.');setLoading(false);return}setLoading(true);setError('');try{const n=String(id).replace(/^tmdb-/i,'').trim(),d=type==='movie'?await fetchMovieDetails(n):await fetchTVDetails(n);if(dead)return;if(!d)throw Error('This title could not be loaded.');setDetails(d);if(type==='tv'&&d.seasons?.length){const s=d.seasons.find(x=>x.season_number>0)?.season_number||1;setSeason(s);const sd=await fetchTVSeasonDetails(n,s);if(!dead)setEpisodes(sd?.episodes||[])}}catch(e){if(!dead)setError(e?.message||'Failed to load details.')}finally{if(!dead)setLoading(false)}})();return()=>{dead=true}},[id,type]);
 useEffect(()=>{let dead=false;if(type==='tv'&&details?.seasons){const n=String(id).replace(/^tmdb-/i,'').trim();fetchTVSeasonDetails(n,season).then(d=>{if(!dead)setEpisodes(d?.episodes||[])}).catch(()=>{})}return()=>{dead=true}},[id,type,season,details]);
 const loadSource=async(s=season,e=episode,p=provider)=>{const n=String(id||'').replace(/^tmdb-/i,'').trim();if(!n)return;setSourceLoading(true);try{const url=await resolveDirectMediaSource(type,n,s,e,p);setSource(url||'')}catch{setSource('')}finally{setSourceLoading(false)}};
 const watch=async()=>{if(!user){setAuthTab('login');navigate?.('profile');return}setPlaying(true);await loadSource()};
 const changeEpisode=async e=>{setEpisode(e);if(playing)await loadSource(season,e)};
 const toggleFs=()=>{if(!playerRef.current)return;if(document.fullscreenElement)document.exitFullscreen();else playerRef.current.requestFullscreen?.()};
 if(loading)return <div className="mobile-content detail-page"><div className="loading-shimmer" style={{height:280,borderRadius:18}}/><div className="loading-shimmer" style={{height:30,width:'65%',marginTop:16,borderRadius:8}}/><div className="loading-shimmer" style={{height:18,width:'90%',marginTop:10,borderRadius:8}}/></div>;
 if(error||!details)return <div className="mobile-content" style={{textAlign:'center',padding:'4rem 1rem'}}><h2>Couldn't load this title</h2><p>{error||'Details unavailable.'}</p><button className="btn-primary" onClick={goBack}>Go Back</button></div>;
 const title=details.title||details.name||initialTitle||'Unknown',poster=details.poster_path?`https://image.tmdb.org/t/p/w500${details.poster_path}`:'',backdrop=details.backdrop_path?`https://image.tmdb.org/t/p/w1280${details.backdrop_path}`:poster,year=(details.release_date||details.first_air_date||'').slice(0,4),rating=Number(details.vote_average||0).toFixed(1),genres=(details.genres||[]).map(g=>g.name).filter(Boolean),seasons=(details.seasons||[]).filter(s=>s.season_number>0);
 if(playing)return <div ref={playerRef} className="player-screen player-screen-v2" style={fullscreen?{padding:0}:undefined}><div className="player-topbar player-topbar-v2"><button className="player-icon-btn" onClick={()=>setPlaying(false)}><ArrowLeft size={20}/></button><div className="player-title"><strong>{title}</strong><span>{type==='movie'?'Movie':`S${season} E${episode}`}</span></div><button className="player-icon-btn" onClick={toggleFs}>{fullscreen?<Minimize size={20}/>:<Maximize size={20}/>}</button></div><div className="player-source-bar">{MEDIA_SOURCE_PROVIDERS.map(p=><button key={p.id} className={p.id===provider?'active':''} onClick={()=>{setProvider(p.id);loadSource(season,episode,p.id)}}>{p.name}</button>)}</div><div className="player-frame-wrap player-frame-wrap-v2">{sourceLoading?<div className="player-loading">Preparing player…</div>:source?<AndroidVideoPlayer sourceUrl={source} poster={poster} title={title} onPrevEpisode={type==='tv'&&episode>1?()=>changeEpisode(episode-1):undefined} onNextEpisode={type==='tv'&&episode<episodes.length?()=>changeEpisode(episode+1):undefined}/>:<div className="player-loading">No playable source returned.</div>}</div>{type==='tv'&&<div className="player-episode-rail"><button className="ply-rail-nav" disabled={episode<=1} onClick={()=>changeEpisode(episode-1)}><SkipBack size={16}/></button><div className="ply-rail-scroll">{episodes.slice(0,100).map(e=><button key={e.episode_number} className={e.episode_number===episode?'active':''} onClick={()=>changeEpisode(e.episode_number)}>{e.episode_number}</button>)}</div><button className="ply-rail-nav" disabled={episode>=episodes.length} onClick={()=>changeEpisode(episode+1)}><SkipForward size={16}/></button></div>}</div>;
 return <div className="mobile-content detail-page" style={{padding:0}}><button className="detail-back" onClick={goBack}><ArrowLeft size={18}/> Back</button><section className="detail-hero" style={{backgroundImage:`linear-gradient(180deg,rgba(3,15,22,.12),rgba(3,15,22,.97)),url(${backdrop})`}}><div className="detail-poster">{poster?<img src={poster} alt={title}/>:null}</div><div className="detail-copy"><h1>{title}</h1><div className="detail-meta"><span>★ {rating}</span>{year&&<span>{year}</span>}<span>{type==='movie'?'MOVIE':'TV SHOW'}</span></div></div></section><div className="detail-content"><div className="detail-actions"><button className="btn-primary" onClick={watch}><Play size={17} fill="currentColor"/> {type==='movie'?'Watch Now':`Watch S${season} E${episode}`}</button></div>{genres.length>0&&<div className="genre-chips-v2">{genres.map(g=><span key={g}>{g}</span>)}</div>}<section className="detail-description-v2"><h2>Overview</h2><p>{details.overview||'No description available.'}</p></section>{type==='tv'&&seasons.length>0&&<section><h2>Seasons</h2><div className="ply-rail-scroll">{seasons.map(s=><button key={s.season_number} className={s.season_number===season?'active':''} onClick={()=>{setSeason(s.season_number);setEpisode(1)}}>Season {s.season_number}</button>)}</div><h2>Episodes</h2><div className="episodes-grid-v2">{episodes.map(e=><button key={e.episode_number} className={e.episode_number===episode?'active':''} onClick={()=>{setEpisode(e.episode_number);watch()}}>{e.episode_number}</button>)}</div></section>}</div></div>;
}
