import React,{useEffect,useMemo,useState} from 'react';
import {Bell,BellOff,Calendar,ChevronRight,Loader,RefreshCw,Film,Tv} from 'lucide-react';
import {useUser} from '../../api/UserContext';
import {requestMobileNotificationPermission,scheduleMobileNotification,cancelMobileNotification} from '../notifications/mobileNotifications';
import {fetchReleaseSchedule} from '../api/movies';
const days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
const fullDays=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const titleOf=x=>x?.title||x?.name||'Unknown';
const imageOf=x=>x?.poster_path?`https://image.tmdb.org/t/p/w342${x.poster_path}`:'/logo.png';
const dateOf=x=>x.releaseTimestamp?new Date(x.releaseTimestamp):null;
const dateLabel=x=>dateOf(x)?.toLocaleDateString([],{month:'short',day:'numeric'})||'TBA';
const timeLabel=x=>dateOf(x)?.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})||'';
const countdown=x=>{const d=Math.max(0,Math.floor((x-releaseNow())/86400000));const h=Math.max(0,Math.floor(((x-releaseNow())%86400000)/3600000));if(d)return `In ${d}d ${h}h`;if(h)return `In ${h}h`;return 'Today'};
const releaseNow=()=>Date.now();
export default function SchedulePage({navigate}){
 const {user,addReminder,removeReminder,isReminded}=useUser();const [data,setData]=useState({movies:[],tv:[]});const [tab,setTab]=useState('tv');const [day,setDay]=useState(new Date().getDay());const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(null);
 const load=async(refresh=false)=>{refresh?setRefreshing(true):setLoading(true);setError('');try{setData(await fetchReleaseSchedule())}catch(e){setError(e?.message||'Failed to load release schedule.')}finally{refresh?setRefreshing(false):setLoading(false)}};
 useEffect(()=>{load()},[]);
 const items=useMemo(()=>{const source=tab==='tv'?data.tv:data.movies;return source.filter(x=>{const d=dateOf(x);return d&&d.getDay()===day}).sort((a,b)=>a.releaseTimestamp-b.releaseTimestamp)},[data,tab,day]);
 const all=tab==='tv'?data.tv:data.movies;const next=all.filter(x=>x.releaseTimestamp>Date.now()).sort((a,b)=>a.releaseTimestamp-b.releaseTimestamp)[0];
 const toggle=async item=>{if(!user)return;const id=`release-${item.media_type}-${item.id}`;setBusy(id);try{if(isReminded(id)){await removeReminder(id);cancelMobileNotification(id);return}const ts=item.releaseTimestamp;if(!ts)return;const permission=await requestMobileNotificationPermission();await addReminder({id,title:titleOf(item),media_id:item.id,media_type:item.media_type,airing_at:Math.floor(ts/1000),image:imageOf(item)});if(permission==='granted')scheduleMobileNotification({id,timestamp:ts,title:`${titleOf(item)} releases`,body:`${titleOf(item)} is scheduled for ${dateLabel(item)}.`,url:`/drama/${item.id}?type=${item.media_type}&title=${encodeURIComponent(titleOf(item))}`})}finally{setBusy(null)}};
 return <div className="av-schedule-v2"><header className="av-schedule-head"><div><span className="av-eyebrow-v2">MOVIES + TV</span><h1>Release Schedule</h1><p>Upcoming movies and TV releases in one place.</p></div><button className="av-schedule-refresh" onClick={()=>load(true)} disabled={refreshing} aria-label="Refresh"><RefreshCw size={18} className={refreshing?'spin':''}/></button></header>
  <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginBottom:14}}><button onClick={()=>setTab('tv')} className={tab==='tv'?'active':''} style={{padding:11,borderRadius:10,border:'1px solid rgba(255,255,255,.08)',background:tab==='tv'?'var(--brand-color)':'rgba(255,255,255,.05)',color:'#fff',fontWeight:700}}><Tv size={16}/> TV Airing</button><button onClick={()=>setTab('movie')} className={tab==='movie'?'active':''} style={{padding:11,borderRadius:10,border:'1px solid rgba(255,255,255,.08)',background:tab==='movie'?'var(--brand-color)':'rgba(255,255,255,.05)',color:'#fff',fontWeight:700}}><Film size={16}/> Movies</button></div>
  {next&&<button className="av-schedule-next" onClick={()=>navigate('drama-detail',{id:next.id,mediaType:next.media_type,title:titleOf(next)})}><img src={imageOf(next)} alt=""/><span className="av-schedule-next-copy"><small>NEXT · {dateLabel(next)} {timeLabel(next)}</small><strong>{titleOf(next)}</strong><span>{countdown(next.releaseTimestamp)}</span></span><ChevronRight size={22}/></button>}
  <div className="av-schedule-days" role="tablist">{days.map((d,i)=><button key={d} role="tab" aria-selected={day===i} className={day===i?'active':''} onClick={()=>setDay(i)}><span>{d}</span><b>{all.filter(x=>dateOf(x)?.getDay()===i).length}</b></button>)}</div>
  {loading?<div className="av-schedule-state"><Loader size={25} className="spin"/><span>Loading releases…</span></div>:error?<div className="av-schedule-state error"><Calendar size={30}/><strong>Schedule unavailable</strong><span>{error}</span><button onClick={()=>load(true)}>Try Again</button></div>:!items.length?<div className="av-schedule-state"><Calendar size={30}/><strong>Nothing scheduled</strong><span>No {tab==='tv'?'TV releases':'movie releases'} are listed for {fullDays[day]}.</span></div>:<section className="av-schedule-list"><div className="av-schedule-list-head"><div><h2>{fullDays[day]}</h2><span>{items.length} release{items.length===1?'':'s'}</span></div></div>{items.map(item=>{const id=`release-${item.media_type}-${item.id}`,reminded=isReminded(id),isBusy=busy===id;return <article className="av-schedule-card" key={id}><button className="av-schedule-card-main" onClick={()=>navigate('drama-detail',{id:item.id,mediaType:item.media_type,title:titleOf(item)})}><img src={imageOf(item)} alt=""/><span><strong>{titleOf(item)}</strong><small>{item.media_type==='tv'?'TV show':'Movie'} · {dateLabel(item)} {timeLabel(item)}</small><em>{item.releaseTimestamp>Date.now()?countdown(item.releaseTimestamp):'Released'}</em></span></button><button className={`av-schedule-reminder ${reminded?'active':''}`} onClick={()=>toggle(item)} disabled={isBusy||!user} title={!user?'Sign in to set reminders':reminded?'Remove reminder':'Set reminder'}>{isBusy?<Loader size={16} className="spin"/>:reminded?<BellOff size={17}/>:<Bell size={17}/>}<span>{reminded?'Reminder set':'Set reminder'}</span></button></article>})}</section>}
 </div>;
}
