import React,{useEffect,useState}from'react';
import{Search,X,Star,Film,Tv,Sparkles}from'lucide-react';
import{searchMoviesAndSeries,fetchLatestMovies,fetchLatestTVShows}from'../api/movies';

const HISTORY_KEY='av_media_search_history';
function Poster({item,onClick}){const title=item?.title||item?.name||'Unknown';const image=item?.poster;const type=item?.mediaType==='movie'||item?.type==='movie'?'Movie':'TV Show';return <button className="av-explore-card" type="button" onClick={()=>onClick(item)}><div className="av-explore-poster">{image?<img src={image} alt={title} loading="lazy"/>:<div className="av-explore-fallback">{type==='Movie'?'🎬':'📺'}</div>} {item?.vote_average&&<span className="av-explore-score"><Star size={9} fill="currentColor"/>{Number(item.vote_average).toFixed(1)}</span>}</div><strong>{title}</strong><small>{type}{item?.year?` · ${item.year}`:''}</small></button>}
export default function SearchPage({navigate}){
 const[q,setQ]=useState(''),[results,setResults]=useState([]),[trending,setTrending]=useState([]),[loading,setLoading]=useState(false),[history,setHistory]=useState(()=>{try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]')}catch{return[]}});
 useEffect(()=>{let cancelled=false;Promise.all([fetchLatestMovies(1),fetchLatestTVShows(1)]).then(([m,t])=>{if(!cancelled)setTrending([...(m||[]),...(t||[])])}).catch(()=>{});return()=>{cancelled=true}},[]);
 useEffect(()=>{const query=q.trim();if(!query){setResults([]);setLoading(false);return}let cancelled=false;const timer=setTimeout(async()=>{setLoading(true);try{const data=await searchMoviesAndSeries(query);if(!cancelled)setResults(data||[])}finally{if(!cancelled)setLoading(false)}},300);return()=>{cancelled=true;clearTimeout(timer)}},[q]);
 const open=item=>{const type=item?.mediaType==='movie'||item?.type==='movie'?'movie':'tv';navigate('drama-detail',{id:item?.tmdbId||item?.id,mediaType:type,title:item?.title||item?.name})};
 const searched=Boolean(q.trim());
 return <div className="av-explore"><section className="av-explore-head"><div><span className="av-explore-kicker"><Sparkles size={12}/> DISCOVER</span><h1>Movies & TV</h1><p>Find movies, dramas and television shows.</p></div></section><div className="av-explore-search-wrap"><Search size={19}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search movies, dramas & TV shows..." aria-label="Search movies and TV shows"/>{q&&<button type="button" onClick={()=>setQ('')}><X size={17}/></button>}</div>
 {!searched&&history.length>0&&<section className="av-explore-section av-history"><header><h2>Recent searches</h2><button onClick={()=>{setHistory([]);localStorage.removeItem(HISTORY_KEY)}}>Clear</button></header><div>{history.map(x=><button key={x} onClick={()=>setQ(x)}>{x}<Search size={12}/></button>)}</div></section>}
 {searched?<section className="av-explore-section"><header><div><h2>{loading?'Searching…':`${results.length} results`}</h2><p>{q.trim()}</p></div></header>{loading?<div className="av-explore-grid">{Array.from({length:6},(_,i)=><div className="av-explore-skeleton" key={i}/>)}</div>:results.length?<div className="av-explore-grid">{results.map((x,i)=><Poster key={`${x.mediaType}-${x.id}-${i}`} item={x} onClick={open}/>)}</div>:<div className="av-explore-empty"><Search size={34}/><h3>No movies or TV shows found</h3><p>Try another title.</p></div>}</section>:<section className="av-explore-section"><header><div><h2><TrendingUpIcon/> Trending now</h2><p>Popular movies and TV shows</p></div></header><div className="av-explore-grid">{trending.slice(0,24).map((x,i)=><Poster key={`${x.mediaType}-${x.id}-${i}`} item={x} onClick={open}/>)}</div></section>}
 </div>
}
function TrendingUpIcon(){return <span style={{display:'inline-flex',marginRight:6}}><Film size={17}/></span>}
