import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import AnimeCard from "../components/AnimeCard";
import { fetchTrendingMedia, fetchAnimeBySeason, fetchAnimeByIds } from "../api/anilist";
import { getTrendingBoard } from "../api/db";
import LatestSection from "../components/LatestSection";
import { useUser } from "../api/UserContext";
import { Play, Calendar, Star, Info, Sparkles, ShieldAlert } from "lucide-react";

const SEASONS=["WINTER","SPRING","SUMMER","FALL"];
const YEARS=[2026,2025,2024,2023,2022];
const GENRES=["Action","Adventure","Comedy","Drama","Fantasy","Horror","Mystery","Psychological","Romance","Sci-Fi","Slice of Life","Sports","Supernatural"];
const KIDS_GENRES=["Adventure","Comedy","Fantasy","Slice of Life","Sports"];
const CLASSROOM_OF_THE_ELITE_BANNER="https://occ-0-8407-2219.1.nflxso.net/dnm/api/v6/MgXQGyNr1xbI8tJSYiMWv5kXg5g/AAAABbu2mrfgMEMATRppz3WvutNHbUSBM3rWWq3nIBWGk3n1DgG9GVI1yX5gkfdDK73a0_L0SVQnfKp2HEIMdC9KeAXdmZB7VjTqO8EI0Pyv3C8DvfJtXEYE1mXA9g.jpg?r=6ae";
const FEATURED_SLIDE_FALLBACKS=[
{id:180745,title:{english:"Classroom of the Elite Season 3"},description:"Class D returns to a brutal merit-based school system where alliances, betrayals, and psychological tests decide who can climb to the top.",seasonYear:2024,averageScore:82,format:"TV",bannerImage:CLASSROOM_OF_THE_ELITE_BANNER},
{id:5114,title:{english:"Fullmetal Alchemist: Brotherhood"},description:"Two brothers search for the Philosopher's Stone after a forbidden ritual changes their lives forever.",seasonYear:2009,averageScore:91,format:"TV",bannerImage:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSo32Teh6AEGe5IwXO3EFDefYi89gXy9z50Q&s"},
{id:1535,title:{english:"Death Note"},description:"A genius student discovers a notebook with deadly power and begins a cat-and-mouse war against the world's greatest detective.",seasonYear:2006,averageScore:84,format:"TV",bannerImage:"https://occ-0-8407-444.1.nflxso.net/dnm/api/v6/MgXQGyNr1xbI8tJSYiMWv5kXg5g/AAAABfx1O1beK9b2mjMEQXxmAB3EGCOt-T7B4X1OfSvSvPZzNQ2dSbe77KUr2PCPYBMRBmIojLoOj1GykcqDRZp3G8cOXQjqCYOoyVBC5hysqmyE6jzKAZ5I8oH5KFYw.jpg?r=3bd"},
{id:1735,title:{english:"Naruto: Shippuden"},description:"Naruto continues his journey home with bigger battles, stronger rivals, and the dream of becoming Hokage still burning bright.",seasonYear:2007,averageScore:82,format:"TV",bannerImage:"https://static0.colliderimages.com/wordpress/wp-content/uploads/2025/02/naruto-header.jpg?w=1200&h=675&fit=crop"},
{id:1,title:{english:"Cowboy Bebop"},description:"A crew of bounty hunters chases criminals across space while their pasts slowly catch up with them.",seasonYear:1998,averageScore:86,format:"TV",bannerImage:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFKyfoTGfnUGfst-p3uNe3DzlnCBKoEDY37A&s"}
];
const KIDS_ANIME_HOME=[
{id:21,title:{english:"One Piece"},description:"A bright pirate adventure about friendship, courage, and chasing big dreams across the seas.",seasonYear:1999,averageScore:89,format:"TV",bannerImage:"https://static1.cbrimages.com/wordpress/wp-content/uploads/2024/01/one-piece-anime-straw-hats.jpg",coverImage:{extraLarge:"https://cdn.myanimelist.net/images/anime/6/73245.jpg"}},
{id:20,title:{english:"Naruto"},description:"Naruto trains with friends, faces rivals, and works toward becoming the best ninja in his village.",seasonYear:2002,averageScore:79,format:"TV",bannerImage:"https://static0.gamerantimages.com/wordpress/wp-content/uploads/2024/05/naruto-main-characters.jpg",coverImage:{extraLarge:"https://cdn.myanimelist.net/images/anime/13/17405.jpg"}},
{id:527,title:{english:"Pokémon"},description:"Ash and Pikachu travel, meet new friends, and discover amazing creatures in every region.",seasonYear:1997,averageScore:72,format:"TV",bannerImage:"https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season01/season01_ep01_ss01.jpg",coverImage:{extraLarge:"https://cdn.myanimelist.net/images/anime/13/73834.jpg"}}
];
function getTitle(a){return a?.title?.english||a?.title?.romaji||a?.title?.native||"Unknown Title"}
function getImage(a){return a?.coverImage?.extraLarge||a?.coverImage?.large||a?.coverImage?.medium||"/logo.png"}
function getDescription(a){return a?.description?.replace(/<[^>]+>/g,"")||"No description available."}
function mergeFeatured(fallback,fetched){return {...fallback,...fetched,title:fetched?.title||fallback.title,description:fetched?.description||fallback.description,bannerImage:fallback.bannerImage||fetched?.bannerImage,coverImage:fetched?.coverImage||fallback.coverImage,seasonYear:fetched?.seasonYear||fallback.seasonYear,averageScore:fetched?.averageScore||fallback.averageScore,format:fetched?.format||fallback.format}}

function Home(){
 const [animeList,setAnimeList]=useState([]),[featuredSlides,setFeaturedSlides]=useState(FEATURED_SLIDE_FALLBACKS),[seasonalList,setSeasonalList]=useState([]),[loading,setLoading]=useState(true),[seasonalLoading,setSeasonalLoading]=useState(false),[selectedSeason,setSelectedSeason]=useState("SPRING"),[selectedYear,setSelectedYear]=useState(2026),[activeSlide,setActiveSlide]=useState(0); const navigate=useNavigate(); const {activeSubAccount}=useUser(); const isKidsProfile=activeSubAccount?.ageRating==="kids";
 const [favoritesData,setFavoritesData]=useState(()=>{try{const x=JSON.parse(localStorage.getItem("animevault_favorites")||"{}");return {animes:Array.isArray(x.animes)?x.animes:[],studios:Array.isArray(x.studios)?x.studios:[],characters:Array.isArray(x.characters)?x.characters:[]}}catch{return {animes:[],studios:[],characters:[]}}});
 useEffect(()=>{let cancelled=false;async function load(){if(isKidsProfile){setAnimeList(KIDS_ANIME_HOME);setFeaturedSlides(KIDS_ANIME_HOME);setLoading(false);return} setLoading(true);try{setFeaturedSlides(FEATURED_SLIDE_FALLBACKS);setLoading(false);const [data,dbFeatured]=await Promise.all([fetchTrendingMedia("ANIME",1,12).catch(()=>[]),getTrendingBoard("anime").catch(()=>[])]);if(cancelled)return;setAnimeList(Array.isArray(data)?data:[]);const base=Array.isArray(dbFeatured)&&dbFeatured.length?dbFeatured.slice(0,5).map(item=>({id:item.media_id,title:{english:item.title},description:item.description||"No description available.",bannerImage:item.banner_url,coverImage:{extraLarge:item.image_url},seasonYear:new Date().getFullYear(),averageScore:80,format:"TV"})):FEATURED_SLIDE_FALLBACKS;const ids=base.map(x=>x.id).filter(Boolean);const enriched=await fetchAnimeByIds(ids).catch(()=>[]);if(cancelled)return;setFeaturedSlides(base.map(f=>mergeFeatured(f,(enriched||[]).find(a=>Number(a.id)===Number(f.id)))).slice(0,5))}catch(e){if(!cancelled)console.warn("Homepage data load failed:",e)}}load();return()=>{cancelled=true}},[isKidsProfile]);
 useEffect(()=>{let cancelled=false;async function load(){if(isKidsProfile){setSeasonalList(KIDS_ANIME_HOME.slice().reverse());setSeasonalLoading(false);return}setSeasonalLoading(true);const data=await fetchAnimeBySeason(selectedSeason,selectedYear).catch(()=>[]);if(!cancelled)setSeasonalList(Array.isArray(data)?data:[]);if(!cancelled)setSeasonalLoading(false)}load();return()=>{cancelled=true}},[selectedSeason,selectedYear,isKidsProfile]);
 useEffect(()=>{if(featuredSlides.length<2)return;const id=setInterval(()=>setActiveSlide(p=>(p+1)%Math.min(5,featuredSlides.length)),6000);return()=>clearInterval(id)},[featuredSlides.length]);
 const trending=animeList.slice(0,12),genresToShow=isKidsProfile?KIDS_GENRES:GENRES;
 function toggleFavorite(anime){setFavoritesData(cur=>{const a=Array.isArray(cur.animes)?cur.animes:[],exists=a.some(x=>x?.id===anime.id),next={...cur,animes:exists?a.filter(x=>x?.id!==anime.id):[...a,{id:anime.id,title:getTitle(anime),image:getImage(anime)}]};try{localStorage.setItem("animevault_favorites",JSON.stringify(next))}catch{}return next})}
 return <section className="home-v2">
  {featuredSlides.length>0&&<div className="hero-v2 hero-carousel-v2 anime-hero-carousel" style={{position:"relative",overflow:"hidden",height:"min(520px, 72vh)"}}>{featuredSlides.slice(0,5).map((anime,index)=>{const active=index===activeSlide;return <div key={anime.id} className={`carousel-slide ${active?"active":""}`} style={{position:"absolute",inset:0,width:"100%",height:"100%",opacity:active?1:0,visibility:active?"visible":"hidden",transition:"opacity .6s ease",zIndex:active?2:1}}><div className="hero-img-wrapper" style={{width:"100%",height:"100%"}}><img src={anime.bannerImage||getImage(anime)} alt={getTitle(anime)} loading={index===0?"eager":"lazy"} fetchPriority={index===0?"high":"low"} decoding="async" style={{width:"100%",height:"100%",objectFit:"cover"}}/><div className="hero-overlay-v2"/></div><div className="hero-content-v2" style={{position:"relative",zIndex:5}}><div className="hero-info-v2"><span className="hero-rank"><Sparkles size={14}/> #{index+1} {isKidsProfile?"Kids Pick":"Trending Classic"}</span><h1 className="hero-title-v2">{getTitle(anime)}</h1><div className="hero-meta-v2"><span><Calendar size={16}/> {anime?.seasonYear||"—"}</span><span><Star size={16}/> {anime?.averageScore||"—"}%</span><span>{anime?.format||"TV"}</span></div><p className="hero-desc-v2">{getDescription(anime).slice(0,220)}...</p><div className="hero-btns-v2"><button className="btn-play-v2" onClick={()=>navigate(`/anime/${anime.id}`)}><Play size={20} fill="black"/> Watch Now</button><button className="btn-info-v2" onClick={()=>navigate(`/anime/${anime.id}`)}><Info size={20}/> Details</button></div></div></div></div>})}<div className="carousel-dots">{featuredSlides.slice(0,5).map((_,i)=><button key={i} aria-label={`Slide ${i+1}`} onClick={()=>setActiveSlide(i)} className={i===activeSlide?"active":""}/>)}</div></div>}
  <div className="home-main-v2"><div className="security-notice-v2"><ShieldAlert size={28}/><div><p><strong>Security & Stability Update</strong> Stable Zen Mode added. Removed restrictive attributes for server compatibility.</p></div></div>{!isKidsProfile&&<LatestSection/>}<section className="home-section-v2"><div className="section-header-v2"><div style={{display:"flex",alignItems:"center",gap:"1rem",flexWrap:"wrap"}}><h2>{isKidsProfile?"Kids Anime Adventures":"Seasonal Browser"}</h2><div className="seasonal-controls-v2"><select value={selectedSeason} onChange={e=>setSelectedSeason(e.target.value)} className="server-dropdown-v2">{SEASONS.map(s=><option key={s}>{s}</option>)}</select><select value={selectedYear} onChange={e=>setSelectedYear(Number(e.target.value))} className="server-dropdown-v2">{YEARS.map(y=><option key={y}>{y}</option>)}</select></div></div></div>{seasonalLoading?<div className="section-loading">Loading seasonal anime…</div>:<div className="anime-grid-v2">{seasonalList.slice(0,12).map(a=><AnimeCard key={a.id} anime={a} isFavorite={(favoritesData.animes||[]).some(x=>x?.id===a.id)} onToggleFavorite={()=>toggleFavorite(a)}/>)}</div>}</section><section className="home-section-v2"><div className="section-header-v2"><h2>Trending Now</h2></div><div className="anime-grid-v2">{trending.map(a=><AnimeCard key={a.id} anime={a} isFavorite={(favoritesData.animes||[]).some(x=>x?.id===a.id)} onToggleFavorite={()=>toggleFavorite(a)}/>)}</div></section><section className="home-section-v2"><div className="section-header-v2"><h2>Explore Genres</h2></div><div className="genre-grid-v2">{genresToShow.map(g=><button key={g} onClick={()=>navigate(`/search?genre=${encodeURIComponent(g)}&type=ANIME`)}>{g}</button>)}</div></section></div>
 </section>}
export default Home;
