import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Play, Calendar, Star, Info, Sparkles, ChevronRight } from 'lucide-react';
import AnimeCard from '../components/AnimeCard';
import { fetchTrendingMedia, fetchAnimeBySeason, fetchAnimeByIds } from '../api/anilist';
import { fetchLatestMovies, fetchLatestTVShows, fetchTMDBBanner } from '../api/movies';

const SEASONS=['WINTER','SPRING','SUMMER','FALL'];
const YEARS=[2026,2025,2024,2023,2022];
const FEATURED_SLIDE_FALLBACKS=[
{id:1535,title:{english:'Death Note'},description:'A genius student discovers a notebook with deadly power and begins a cat-and-mouse war against the world’s greatest detective.',bannerImage:'https://animeblog.github.io/images/death-note-banner.jpg',coverImage:{extraLarge:'https://cdn.europosters.eu/image/hp/60720.jpg'},seasonYear:2006,averageScore:84,format:'TV'},
{id:999999,title:{english:'Spider-Man: Brand New Day'},tmdbSearchTitle:'Spider-Man: Brand New Day',tmdbMediaType:'movie',description:'Spider-Man faces a brand new day of crime-fighting while balancing school, friends, and a new era of heroes.',bannerImage:'https://i.imgur.com/7Y3aZgE.jpg',coverImage:{extraLarge:'https://i.imgur.com/7Y3aZgE.jpg'},seasonYear:2024,averageScore:88,format:'MOVIE'},
{id:180745,title:{english:'Solo Leveling'},tmdbSearchTitle:'Solo Leveling',tmdbMediaType:'tv',description:'A weak hunter discovers the power to grow stronger with every battle, changing his fate forever.',bannerImage:'https://i.imgur.com/8qTm0XE.jpg',coverImage:{extraLarge:'https://i.imgur.com/8qTm0XE.jpg'},seasonYear:2024,averageScore:89,format:'TV'},
{id:888888,title:{english:'When I Fly Towards You'},tmdbSearchTitle:'When I Fly Towards You',tmdbMediaType:'tv',description:'A romantic drama about first love, dreams, and the courage to follow your heart as two people grow closer.',bannerImage:'https://i.imgur.com/3KX9iLz.jpg',coverImage:{extraLarge:'https://i.imgur.com/3KX9iLz.jpg'},seasonYear:2024,averageScore:86,format:'DRAMA'}
];
function getTitle(a){return a?.title?.english||a?.title?.romaji||a?.title?.native||'Unknown Title'}
function getImage(a){return a?.coverImage?.extraLarge||a?.coverImage?.large||a?.coverImage?.medium||a?.coverImage?.original||'/logo.png'}
function getBanner(a){return a?.bannerImage||getImage(a)}
function getDescription(a){return a?.description?.replace(/<[^>]+>/g,'')||'No description available.'}

export default function MixedHome(){
 const [animeList,setAnimeList]=useState([]),[featuredSlides,setFeaturedSlides]=useState(FEATURED_SLIDE_FALLBACKS),[seasonalList,setSeasonalList]=useState([]),[movies,setMovies]=useState([]),[tvShows,setTvShows]=useState([]),[loading,setLoading]=useState(true),[seasonalLoading,setSeasonalLoading]=useState(true),[selectedSeason,setSelectedSeason]=useState('SPRING'),[selectedYear,setSelectedYear]=useState(2026),[activeSlide,setActiveSlide]=useState(0);const navigate=useNavigate();const[favoritesData,setFavoritesData]=useState(()=>{try{const x=JSON.parse(localStorage.getItem('animevault_favorites')||'{}');return{animes:Array.isArray(x.animes)?x.animes:[],studios:Array.isArray(x.studios)?x.studios:[],characters:Array.isArray(x.characters)?x.characters:[]}}catch{return{animes:[],studios:[],characters:[]}}});const favorites=favoritesData.animes||[];
 useEffect(()=>{let cancelled=false;async function load(){setLoading(true);setFeaturedSlides(FEATURED_SLIDE_FALLBACKS);try{const [animeTrending,latestMovies,latestTv]=await Promise.all([fetchTrendingMedia('ANIME',1,12).catch(()=>[]),fetchLatestMovies(1).catch(()=>[]),fetchLatestTVShows(1).catch(()=>[])]);if(cancelled)return;setAnimeList(Array.isArray(animeTrending)?animeTrending:[]);setMovies(Array.isArray(latestMovies)?latestMovies:[]);setTvShows(Array.isArray(latestTv)?latestTv:[]);const featured=FEATURED_SLIDE_FALLBACKS.slice();const enriched=await fetchAnimeByIds(featured.map(x=>x.id)).catch(()=>[]);if(cancelled)return;const merged=featured.map(f=>{const a=enriched.find(x=>Number(x.id)===Number(f.id));return{...f,...a,title:a?.title||f.title,bannerImage:f.bannerImage||a?.bannerImage,coverImage:a?.coverImage||f.coverImage,seasonYear:a?.seasonYear||f.seasonYear,averageScore:a?.averageScore||f.averageScore,format:a?.format||f.format}});setFeaturedSlides(merged);for(let i=0;i<merged.length;i++){const slide=merged[i];if(!slide.tmdbSearchTitle)continue;fetchTMDBBanner(slide.tmdbSearchTitle,slide.tmdbMediaType).then(b=>{if(!cancelled&&b)setFeaturedSlides(cur=>cur.map(x=>x.id===slide.id?{...x,bannerImage:b}:x))}).catch(()=>{})}}catch(e){if(!cancelled)console.warn('Failed to load mixed homepage content:',e)}finally{if(!cancelled)setLoading(false)}}load();return()=>{cancelled=true}},[]);
 useEffect(()=>{let cancelled=false;setSeasonalLoading(true);fetchAnimeBySeason(selectedSeason,selectedYear).then(x=>{if(!cancelled)setSeasonalList(Array.isArray(x)?x:[])}).catch(()=>{}).finally(()=>{if(!cancelled)setSeasonalLoading(false)});return()=>{cancelled=true}},[selectedSeason,selectedYear]);
 useEffect(()=>{const count=Math.min(5,featuredSlides.length);if(count<2)return;const interval=setInterval(()=>setActiveSlide(p=>(p+1)%count),6500);return()=>clearInterval(interval)},[featuredSlides.length]);
 function toggleFavorite(anime){setFavoritesData(current=>{const list=Array.isArray(current.animes)?current.animes:[],isFav=list.some(item=>item?.id===anime.id),next={...current,animes:isFav?list.filter(item=>item?.id!==anime.id):[...list,{id:anime.id,title:getTitle(anime),image:getImage(anime)}]};try{localStorage.setItem('animevault_favorites',JSON.stringify(next))}catch{}return next})}
 const trendingAnime=animeList.slice(0,12);
 return <section className="home-v2">
  <div className="hero-v2 hero-carousel-v2 anime-hero-carousel" style={{position:'relative',overflow:'hidden',height:'min(520px,72vh)'}}>{featuredSlides.slice(0,5).map((anime,index)=>{const active=index===activeSlide;return <div key={anime.id} className={`carousel-slide ${active?'active':''}`} style={{position:'absolute',inset:0,width:'100%',height:'100%',opacity:active?1:0,visibility:active?'visible':'hidden',transition:'opacity .6s ease',zIndex:active?2:1}}><div className="hero-img-wrapper" style={{width:'100%',height:'100%'}}><img src={getBanner(anime)} alt={getTitle(anime)} loading={index===0?'eager':'lazy'} fetchPriority={index===0?'high':'low'} decoding="async" style={{width:'100%',height:'100%',objectFit:'cover'}}/><div className="hero-overlay-v2"/></div><div className="hero-content-v2" style={{position:'relative',zIndex:5}}><div className="hero-info-v2" style={{transform:active?'translateY(0)':'translateY(20px)',opacity:active?1:0,transition:'opacity .4s,transform .4s'}}><span className="hero-rank" style={{color:'var(--brand-color)',background:'rgba(0,0,0,.6)',border:'1px solid var(--brand-color)',display:'inline-flex',alignItems:'center',gap:6,padding:'4px 12px',borderRadius:20,fontSize:'.75rem',fontWeight:'bold',textTransform:'uppercase',width:'fit-content'}}><Sparkles size={14}/> {index+1} Trending Now</span><h1 className="hero-title-v2">{getTitle(anime)}</h1><div className="hero-meta-v2"><span><Calendar size={16}/> {anime?.seasonYear||'TBA'}</span><span><Star size={16}/> {anime?.averageScore||'—'}</span><span>{anime?.format||'Anime'}</span></div><p className="hero-desc-v2">{getDescription(anime).slice(0,220)}...</p><div className="hero-btns-v2"><button className="btn-play-v2" onClick={()=>navigate(`/anime/${anime.id}`)}><Play size={20} fill="black"/> Watch Now</button><button className="btn-info-v2" onClick={()=>navigate(`/anime/${anime.id}`)}><Info size={20}/> Details</button></div></div></div></div>})}<div className="carousel-dots">{featuredSlides.slice(0,5).map((_,i)=><button key={i} aria-label={`Slide ${i+1}`} onClick={()=>setActiveSlide(i)} className={i===activeSlide?'active':''}/>)}</div></div>
  <div className="home-main-v2">
   <div className="section-v2"><div className="section-header-v2"><div><h2>Anime Spotlight</h2><p style={{color:'var(--text-secondary)',margin:0}}>The same anime homepage experience, now alongside movies and dramas.</p></div><Link to="/anime" className="view-all">Explore Anime <ChevronRight size={18}/></Link></div><div className="trending-grid-v2">{trendingAnime.map(anime=><AnimeCard key={anime.id} anime={anime} isFavorite={favorites.some(f=>f?.id===anime.id)} onToggleFavorite={()=>toggleFavorite(anime)}/>)}</div></div>
   <div className="section-v2"><div className="section-header-v2"><div><h2>Seasonal Anime</h2><p style={{color:'var(--text-secondary)',margin:0}}>Fresh titles from the current anime season.</p></div><div style={{display:'flex',gap:'.75rem',flexWrap:'wrap'}}><select value={selectedSeason} onChange={e=>setSelectedSeason(e.target.value)} className="server-dropdown-v2">{SEASONS.map(s=><option key={s}>{s}</option>)}</select><select value={selectedYear} onChange={e=>setSelectedYear(Number(e.target.value))} className="server-dropdown-v2">{YEARS.map(y=><option key={y}>{y}</option>)}</select></div></div><div className="trending-grid-v2" style={{opacity:seasonalLoading?.5:1}}>{seasonalList.slice(0,12).map(anime=><AnimeCard key={anime.id} anime={anime} isFavorite={favorites.some(f=>f?.id===anime.id)} onToggleFavorite={()=>toggleFavorite(anime)}/>)}</div></div>
   <div className="section-v2"><div className="section-header-v2"><div><h2>Blockbuster Movies</h2><p style={{color:'var(--text-secondary)',margin:0}}>Watch the latest movies and top box office hits.</p></div><Link to="/dramas-movies" className="view-all">Explore Movies <ChevronRight size={18}/></Link></div><div className="trending-grid-v2">{movies.slice(0,8).map(movie=><Link key={movie.id} to={`/watch/movie/${movie.id}`} className="anime-card-v2" style={{textDecoration:'none'}}><div className="card-media"><img src={movie.poster} alt={movie.title} loading="lazy" decoding="async"/><div className="card-overlay"><div className="play-icon-wrapper"><Play fill="white" size={24}/></div></div></div><div className="card-info"><h3 className="card-title">{movie.title}</h3><div className="card-meta"><span>MOVIE</span>{movie.year&&<><span className="dot">•</span><span>{movie.year}</span></>}</div></div></Link>)}</div></div>
   <div className="section-v2"><div className="section-header-v2"><div><h2>Trending Dramas & Shows</h2><p style={{color:'var(--text-secondary)',margin:0}}>Stream today’s top series and drama picks.</p></div><Link to="/dramas-movies" className="view-all">Explore Shows <ChevronRight size={18}/></Link></div><div className="trending-grid-v2">{tvShows.slice(0,8).map(show=><Link key={show.id} to={`/watch/tv/${show.id}`} className="anime-card-v2" style={{textDecoration:'none'}}><div className="card-media"><img src={show.poster} alt={show.title} loading="lazy" decoding="async"/><div className="card-overlay"><div className="play-icon-wrapper"><Play fill="white" size={24}/></div></div></div><div className="card-info"><h3 className="card-title">{show.title}</h3><div className="card-meta"><span>TV SHOW</span>{show.year&&<><span className="dot">•</span><span>{show.year}</span></>}</div></div></Link>)}</div></div>
  </div>
 </section>
}
