import React,{useEffect,useMemo,useState}from'react';
import{Calendar,Film,Tv,Clock,RefreshCw,Play}from'lucide-react';

const KEY='288d312680f3117dd4c56964be6809dc';
const BASE='https://api.themoviedb.org/3';
const IMG='https://image.tmdb.org/t/p/w500';
const BACKDROP='https://image.tmdb.org/t/p/w780';
function dayString(offset=0){const d=new Date();d.setDate(d.getDate()+offset);return d.toISOString().slice(0,10)}
async function get(path,params){const u=new URL(`${BASE}${path}`);u.searchParams.set('api_key',KEY);u.searchParams.set('language','en-US');Object.entries(params||{}).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u);if(!r.ok)throw new Error(`TMDB ${r.status}`);return r.json()}
function Card({item,type}){const title=item.title||item.name;const poster=item.poster_path?`${IMG}${item.poster_path}`:'';const date=item.release_date||item.first_air_date;return <article className="media-schedule-card"><div className="media-schedule-poster">{poster?<img src={poster} alt={title}/>:<div className="media-schedule-placeholder">{type==='movie'?<Film/>:<Tv/>}</div>}<span className="media-schedule-badge">{type==='movie'?'MOVIE':'TV'}</span></div><div className="media-schedule-card-body"><h3>{title}</h3><p>{date||'TBA'} {item.vote_average?` · ★ ${Number(item.vote_average).toFixed(1)}`:''}</p><button onClick={()=>{window.location.hash=`#/watch/${type}/${item.id}`}}><Play size={14} fill="currentColor"/> Watch</button></div></article>}
export default function MediaSchedule(){const[day,setDay]=useState(0),[movies,setMovies]=useState([]),[shows,setShows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');const date=dayString(day);useEffect(()=>{let dead=false;setLoading(true);setError('');Promise.all([get('/discover/movie',{primary_release_date_gte:date,primary_release_date_lte:date,sort_by:'popularity.desc',page:1}),get('/discover/tv',{air_date_gte:date,air_date_lte:date,sort_by:'popularity.desc',page:1})]).then(([m,t])=>{if(dead)return;setMovies(m.results||[]);setShows(t.results||[])}).catch(e=>{if(!dead)setError(e.message||'Unable to load schedule')}).finally(()=>{if(!dead)setLoading(false)});return()=>{dead=true}},[date]);const days=useMemo(()=>Array.from({length:7},(_,i)=>({offset:i,label:i===0?'TODAY':new Date(dayString(i)).toLocaleDateString(undefined,{weekday:'short'}),date:dayString(i)})),[]);return <main className="media-schedule-page"><header className="media-schedule-header"><div><span><Calendar size={15}/> RELEASE CALENDAR</span><h1>Movies & TV Schedule</h1><p>Movies releasing and TV shows airing each day.</p></div><button onClick={()=>setDay(0)}><RefreshCw size={15}/> Today</button></header><div className="media-schedule-days">{days.map(d=><button key={d.offset} className={day===d.offset?'active':''} onClick={()=>setDay(d.offset)}><strong>{d.label}</strong><small>{d.date.slice(5)}</small></button>)}</div>{loading?<div className="media-schedule-state"><Clock className="spin"/> Loading schedule…</div>:error?<div className="media-schedule-state error">{error}</div>:<><section><div className="media-schedule-section-title"><h2><Film size={19}/> Movies releasing</h2><span>{movies.length}</span></div>{movies.length?<div className="media-schedule-grid">{movies.slice(0,24).map(x=><Card key={x.id} item={x} type="movie"/>)}</div>:<div className="media-schedule-empty">No movie releases listed for this date.</div>}</section><section><div className="media-schedule-section-title"><h2><Tv size={19}/> TV shows airing</h2><span>{shows.length}</span></div>{shows.length?<div className="media-schedule-grid">{shows.slice(0,24).map(x=><Card key={x.id} item={x} type="tv"/>)}</div>:<div className="media-schedule-empty">No TV episodes listed for this date.</div>}</section></>}</main>}
